export * from './generic-model.model';
export * from './model-insert-torneo.model';
export * from './model-insert-equipo.model';
export * from './model-update-foto-perfil.model';
export * from './vincular-jugador-equipo.model';
export * from './model-insert-equipo-torneo.model';
export * from './modelo-codigo-qr.model';
export * from './model-insert-evento.model';
export * from './model-registrar-usuario-evento.model';
